### ISSUE TITLE
Problem with lockfiles

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/reportengine#30]
I'm getting the following error using the latest version of `reportengine`

```
Traceback (most recent call last):
  File "/media/storageSSD/Academic_Workspace/NNPDF/source/nnpdf/n3fit/src/n3fit/n3fit.py", line 193, in run
    super().run()
  File "/media/storageSSD/Academic_Workspace/NNPDF/source/nnpdf/validphys2/src/validphys/app.py", line 144, in run
    super().run()
  File "/media/storageSSD/Academic_Workspace/NNPDF/source/reportengine/src/reportengine/app.py", line 353, in run
    c.dump_lockfile()
  File "/media/storageSSD/Academic_Workspace/NNPDF/source/reportengine/src/reportengine/configparser.py", line 803, in dump_lockfile
    with open(self.environment.input_folder/"lockfile.yaml", "w+") as f:
AttributeError: 'N3FitEnvironment' object has no attribute 'input_folder'
```

For now I'm staying at 901aa52686e2f2b96e96d766af32aa5499c84793 which was working fine

Things that might or not be relevant:
- I am not using conda (in conda it seems to work fine, not sure whether the conda version of reportengine is up to date)
- I've done a fresh installation of nnpdf (and all dependencies)
- I'm using python 3.8.2

(not sure whether I should've changed something in `n3fit` to accommodate the changes)

**Comment by Zaharid** [comment]
I think the best thing to do is to make sure all environment classes have `input_folder`. It's part of the interface anyway.

**Comment by wilsonmr** [comment]
yeah I guess I don't have much to add, I think I just assumed the input_folder would always be created... I guess vp-setupfit and postfit could also be affected by this change

**Comment by wilsonmr** [comment]
perhaps could check that input_folder exists before dumping the lockfile?

**Comment by Zaharid** [comment]
Nah, really let's just add it to the environments. We want lockfiles in
n3fit anyway.

**Comment by Zaharid** [comment]
This is now fixed in NNPDF.
